version: "3"

services:
  db:
    container_name: c43db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: a
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: c43pgdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5430:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  server:
    container_name: c43server
    build: ./backend
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: a
      DB_NAME: c43pgdb
  app:
    container_name: c43app
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
